<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo" ignored="0" name="Test" tests="10" failures="2" timestamp="19 Apr 2020 11:29:36 GMT" time="0.533" errors="0">
  <testcase name="firsttest" time="0.032" classname="testngSample.SeconfTestng"/>
  <testcase name="fourthTest" time="0.016" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- fourthTest -->
  <testcase name="fourthTest" time="0.015" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- fourthTest -->
  <testcase name="fourthTest" time="0.0" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- fourthTest -->
  <testcase name="fourthTest" time="0.0" classname="testngSample.SeconfTestng">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngSample.SeconfTestng.fourthTest(SeconfTestng.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- fourthTest -->
  <testcase name="secondTest" time="0.016" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- secondTest -->
  <testcase name="secondTest" time="0.015" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- secondTest -->
  <testcase name="secondTest" time="0.047" classname="testngSample.SeconfTestng">
    <skipped/>
  </testcase> <!-- secondTest -->
  <testcase name="secondTest" time="0.016" classname="testngSample.SeconfTestng">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngSample.SeconfTestng.secondTest(SeconfTestng.java:15)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- secondTest -->
  <testcase name="thirdTest" time="0.016" classname="testngSample.SeconfTestng"/>
</testsuite> <!-- Test -->
